import { lazy, Suspense, useState, type FormEvent } from 'react'
import { BrowserRouter, Navigate, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { ArrowRight, LockKeyhole } from 'lucide-react'
import { useSession } from './providers'
import { readableError } from '../api/client'
import { AppLayout } from '../layouts/AppLayout'
import { Button, EmptyState, LoadingSkeleton, ToastProvider } from '../components/ui'

const DashboardPage = lazy(() => import('../features/dashboard/DashboardPage').then(m => ({ default: m.DashboardPage })))
const ResourceDetailPage = lazy(() => import('../features/resources/ResourcePages').then(m => ({ default: m.ResourceDetailPage })))
const ResourceFormPage = lazy(() => import('../features/resources/ResourcePages').then(m => ({ default: m.ResourceFormPage })))
const ResourceListPage = lazy(() => import('../features/resources/ResourcePages').then(m => ({ default: m.ResourceListPage })))
const DocumentFormPage = lazy(() => import('../features/documents/DocumentFormPage').then(m => ({ default: m.DocumentFormPage })))
const PosPage = lazy(() => import('../features/pos/PosPage').then(m => ({ default: m.PosPage })))
const InventoryOverviewPage = lazy(() => import('../features/operations/OverviewPages').then(m => ({ default: m.InventoryOverviewPage })))
const FinanceOverviewPage = lazy(() => import('../features/operations/OverviewPages').then(m => ({ default: m.FinanceOverviewPage })))
const CrmPipelinePage = lazy(() => import('../features/operations/OverviewPages').then(m => ({ default: m.CrmPipelinePage })))
const ReportsPage = lazy(() => import('../features/reports/ReportsPage').then(m => ({ default: m.ReportsPage })))
const SettingsPage = lazy(() => import('../features/settings/SettingsPage').then(m => ({ default: m.SettingsPage })))
const ProductDetailPage = lazy(() => import('../features/products/ProductsPage').then(m => ({ default: m.ProductDetailPage })))
const ProductsPage = lazy(() => import('../features/products/ProductsPage').then(m => ({ default: m.ProductsPage })))

function LoginPage(){const {login}=useSession();const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await login(username,password)}catch(err){setError(readableError(err))}finally{setBusy(false)}};return <div className="login-screen"><section className="login-visual"><div className="login-brand"><span className="brand-symbol">N<span>×</span></span>NEXORA ERP</div><div><div className="eyebrow" style={{color:'#aab6ff'}}>ЕДИНАЯ ПЛАТФОРМА УПРАВЛЕНИЯ</div><h1>Весь бизнес.<br/>Одна точка контроля.</h1><p>Продажи, закупки, склад, финансы и команда в единой системе с ясными данными и быстрыми действиями.</p></div><footer>© {new Date().getFullYear()} NEXORA · Enterprise workspace</footer></section><section className="login-panel"><form className="login-form" onSubmit={submit}><div className="eyebrow">БЕЗОПАСНЫЙ ВХОД</div><h2>Добро пожаловать</h2><p>Введите данные вашей учётной записи, чтобы продолжить работу.</p><label className="form-field"><span>Имя пользователя</span><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required placeholder="username"/></label><label className="form-field"><span>Пароль</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/></label>{error&&<div className="login-error">{error}</div>}<Button variant="primary" className="button-wide" disabled={busy}><LockKeyhole size={16}/>{busy?'Вход…':'Войти в систему'}<ArrowRight size={16}/></Button></form></section></div>}
function FormRoute(){const {key}=useParams();return key==='sales'||key==='purchases'?<DocumentFormPage/>:<ResourceFormPage/>}
function LegacyRoute(){const location=useLocation();return <Navigate to={`/m${location.pathname}${location.search}`} replace/>}
export default function App(){const {user,loading}=useSession();if(loading)return <div className="login-screen"><div className="login-panel" style={{gridColumn:'1/-1'}}>Загрузка рабочего пространства…</div></div>;if(!user)return <LoginPage/>;return <ToastProvider><BrowserRouter><Suspense fallback={<div className="page-content"><LoadingSkeleton/></div>}><Routes><Route element={<AppLayout/>}><Route index element={<DashboardPage/>}/><Route path="inventory" element={<InventoryOverviewPage/>}/><Route path="finance" element={<FinanceOverviewPage/>}/><Route path="crm" element={<CrmPipelinePage/>}/><Route path="pos" element={<PosPage/>}/><Route path="reports" element={<ReportsPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="m/products" element={<ProductsPage/>}/><Route path="m/products/new" element={<ResourceFormPage/>}/><Route path="m/products/:id" element={<ProductDetailPage/>}/><Route path="m/:key" element={<ResourceListPage/>}/><Route path="m/:key/new" element={<FormRoute/>}/><Route path="m/:key/:id/edit" element={<ResourceFormPage/>}/><Route path="m/:key/:id" element={<ResourceDetailPage/>}/><Route path="products/*" element={<LegacyRoute/>}/><Route path="sales/*" element={<LegacyRoute/>}/><Route path="404" element={<EmptyState title="Страница не найдена" description="Проверьте адрес или выберите раздел в меню."/>}/><Route path="*" element={<Navigate to="/404"/>}/></Route></Routes></Suspense></BrowserRouter></ToastProvider>}
