import type { Resource, Column, Field } from '../types'

const c = (key:string,label:string,type:Column['type']='text',link=false):Column => ({key,label,type,link})
const f = (key:string,label:string,type:Field['type']='text',required=false,endpoint?:string):Field => ({key,label,type,required,endpoint})
const org = f('organization','Организация','select',true,'organizations/')
const date = f('date','Дата','datetime',true)
const number = f('number','Номер документа','text',true)
const comment = f('comment','Комментарий','textarea')
const name = f('name','Название','text',true)
const status = c('status','Статус','status')
const created = c('created_at','Создано','datetime')
const amount = c('total_amount','Сумма','money')
const resources: Resource[] = [
  {key:'products',title:'Товары',subtitle:'Номенклатура, цены и остатки',endpoint:'products/',icon:'Package',search:['name','sku','barcode'],columns:[c('sku','SKU','text',true),c('name','Наименование','text',true),c('category','Категория'),c('purchase_price','Закупка','money'),c('sale_price','Продажа','money'),c('min_stock','Мин. запас','number'),c('is_active','Активен','boolean'),c('updated_at','Изменено','datetime')],fields:[org,name,f('sku','SKU','text',true),f('barcode','Штрихкод'),f('category','Категория','select',false,'categories/'),f('brand','Бренд','select',false,'brands/'),f('unit','Единица','select',false,'units/'),f('description','Описание','textarea'),f('purchase_price','Закупочная цена','money'),f('sale_price','Цена продажи','money'),f('min_stock','Минимальный остаток','number'),f('tax_percent','Налог, %','number'),f('is_service','Услуга','boolean'),f('is_active','Активен','boolean')],create:true,edit:true,exportPath:'export/excel/products/',permission:undefined},
  {key:'categories',title:'Категории',subtitle:'Структура товарного каталога',endpoint:'categories/',icon:'Layers3',columns:[c('name','Категория','text',true),c('parent','Родительская'),c('is_active','Активна','boolean')],fields:[org,name,f('parent','Родительская','select',false,'categories/'),f('is_active','Активна','boolean')],create:true,edit:true},
  {key:'brands',title:'Бренды',subtitle:'Производители и торговые марки',endpoint:'brands/',icon:'BadgeCheck',columns:[c('name','Бренд','text',true)],fields:[org,name],create:true,edit:true},
  {key:'units',title:'Единицы измерения',subtitle:'Справочник единиц',endpoint:'units/',icon:'Ruler',columns:[c('name','Название','text',true),c('short_name','Сокращение')],fields:[org,name,f('short_name','Сокращение','text',true)],create:true,edit:true},
  {key:'price-types',title:'Прайс-листы',subtitle:'Типы цен и тарифы',endpoint:'price-types/',icon:'Tags',columns:[c('name','Тип цены','text',true)],fields:[org,name],create:true,edit:true},
  {key:'sales',title:'Заказы на продажу',subtitle:'Продажи, оплаты и отгрузки',endpoint:'sales/',icon:'ReceiptText',columns:[c('number','Номер','text',true),c('customer','Клиент'),c('warehouse','Склад'),c('date','Дата','datetime'),amount,c('paid_amount','Оплачено','money'),c('payment_status','Оплата','status'),status],fields:[org,number,date,f('customer','Клиент','select',true,'counterparties/'),f('warehouse','Склад','select',true,'warehouses/'),f('paid_amount','Оплачено','money'),comment],create:true,edit:true,permission:'sales',exportPath:'export/excel/sales/'},
  {key:'sale-returns',title:'Возвраты покупателей',subtitle:'Возврат товаров и корректировки',endpoint:'sale-returns/',icon:'RotateCcw',columns:[c('number','Номер','text',true),c('sale','Продажа'),c('warehouse','Склад'),status,created],fields:[number,f('sale','Продажа','select',true,'sales/'),f('warehouse','Склад','select',true,'warehouses/'),comment],create:true,permission:'sales'},
  {key:'purchases',title:'Заказы поставщикам',subtitle:'Закупки, поставщики и поступления',endpoint:'purchases/',icon:'ShoppingBag',columns:[c('number','Номер','text',true),c('supplier','Поставщик'),c('warehouse','Склад'),c('date','Дата','datetime'),amount,c('paid_amount','Оплачено','money'),c('payment_status','Оплата','status'),status],fields:[org,number,date,f('supplier','Поставщик','select',true,'counterparties/'),f('warehouse','Склад','select',true,'warehouses/'),f('paid_amount','Оплачено','money'),comment],create:true,permission:'purchases',exportPath:'export/excel/purchases/'},
  {key:'purchase-returns',title:'Возвраты поставщикам',subtitle:'Возврат закупленных товаров',endpoint:'purchase-returns/',icon:'Undo2',columns:[c('number','Номер','text',true),c('purchase','Закупка'),c('warehouse','Склад'),status,created],fields:[number,f('purchase','Закупка','select',true,'purchases/'),f('warehouse','Склад','select',true,'warehouses/'),comment],create:true,permission:'purchases'},
  {key:'customers',title:'Клиенты',subtitle:'Контакты, история заказов и долги',endpoint:'counterparties/',icon:'UsersRound',fixedFilter:{counterparty_type:'CUSTOMER'},search:['name','phone','email'],columns:[c('name','Клиент','text',true),c('phone','Телефон'),c('email','Email'),c('inn','ИНН'),c('opening_balance','Входящий баланс','money'),c('is_active','Активен','boolean')],fields:[org,name,f('counterparty_type','Тип','select',true),f('person_type','Форма','select'),f('phone','Телефон'),f('email','Email'),f('inn','ИНН'),f('address','Адрес'),f('opening_balance','Входящий баланс','money')],create:true,edit:true},
  {key:'suppliers',title:'Поставщики',subtitle:'Контакты, закупки и расчёты',endpoint:'counterparties/',icon:'Truck',fixedFilter:{counterparty_type:'SUPPLIER'},search:['name','phone','email'],columns:[c('name','Поставщик','text',true),c('phone','Телефон'),c('email','Email'),c('inn','ИНН'),c('opening_balance','Входящий баланс','money'),c('is_active','Активен','boolean')],fields:[org,name,f('counterparty_type','Тип','select',true),f('person_type','Форма','select'),f('phone','Телефон'),f('email','Email'),f('inn','ИНН'),f('address','Адрес')],create:true,edit:true},
  {key:'warehouses',title:'Склады',subtitle:'Места хранения и ответственные',endpoint:'warehouses/',icon:'Warehouse',columns:[c('name','Склад','text',true),c('branch','Филиал'),c('address','Адрес'),c('is_active','Активен','boolean')],fields:[org,name,f('branch','Филиал','select',false,'branches/'),f('address','Адрес'),f('is_active','Активен','boolean')],create:true,edit:true,permission:'warehouse'},
  {key:'stocks',title:'Остатки',subtitle:'Наличие товаров по складам',endpoint:'stocks/',icon:'Boxes',columns:[c('product','Товар'),c('warehouse','Склад'),c('quantity','Количество','number'),c('reserved_quantity','Резерв','number'),c('available_quantity','Доступно','number'),c('average_cost','Средняя цена','money'),c('updated_at','Обновлено','datetime')],exportPath:'export/excel/stocks/'},
  {key:'stock-movements',title:'Движения товаров',subtitle:'Журнал складских операций',endpoint:'stock-movements/',icon:'ArrowLeftRight',columns:[c('created_at','Дата','datetime'),c('movement_type','Тип','status'),c('product','Товар'),c('warehouse','Склад'),c('quantity','Количество','number'),c('unit_cost','Цена','money'),c('document_type','Документ')]},
  {key:'stock-transfers',title:'Перемещения',subtitle:'Межскладские перемещения',endpoint:'stock-transfers/',icon:'MoveHorizontal',columns:[c('number','Номер','text',true),c('from_warehouse','Со склада'),c('to_warehouse','На склад'),c('date','Дата','datetime'),status],fields:[org,number,date,f('from_warehouse','Со склада','select',true,'warehouses/'),f('to_warehouse','На склад','select',true,'warehouses/'),comment],create:true,permission:'warehouse'},
  {key:'inventories',title:'Инвентаризации',subtitle:'Сверка фактических и учётных остатков',endpoint:'inventories/',icon:'ClipboardList',columns:[c('number','Номер','text',true),c('warehouse','Склад'),c('date','Дата','datetime'),status,created],fields:[org,number,date,f('warehouse','Склад','select',true,'warehouses/'),comment],create:true,permission:'warehouse'},
  {key:'write-offs',title:'Списания',subtitle:'Контроль выбытия товаров',endpoint:'write-offs/',icon:'PackageX',columns:[c('number','Номер','text',true),c('warehouse','Склад'),c('reason','Причина'),c('date','Дата','datetime'),status],fields:[org,number,date,f('warehouse','Склад','select',true,'warehouses/'),f('reason','Причина','select',true),comment],create:true,permission:'warehouse'},
  {key:'cash-accounts',title:'Кассы и счета',subtitle:'Денежные средства по счетам',endpoint:'cash-accounts/',icon:'Landmark',columns:[c('name','Счёт','text',true),c('account_type','Тип','status'),c('balance','Баланс','money'),c('currency','Валюта'),c('is_active','Активен','boolean')],fields:[org,name,f('account_type','Тип счёта','select',true),f('currency','Валюта'),f('is_active','Активен','boolean')],create:true,edit:true,permission:'finance'},
  {key:'cash-transactions',title:'Платежи',subtitle:'Поступления и списания денежных средств',endpoint:'cash-transactions/',icon:'WalletCards',columns:[c('number','Номер','text',true),c('date','Дата','datetime'),c('transaction_type','Тип','status'),c('account','Счёт'),c('counterparty','Контрагент'),c('amount','Сумма','money'),status],fields:[org,number,date,f('transaction_type','Тип','select',true),f('account','Счёт','select',true,'cash-accounts/'),f('counterparty','Контрагент','select',false,'counterparties/'),f('amount','Сумма','money',true),comment],create:true,permission:'finance',exportPath:'export/excel/cash-transactions/'},
  {key:'money-transfers',title:'Переводы',subtitle:'Перемещение денег между счетами',endpoint:'money-transfers/',icon:'ArrowRightLeft',columns:[c('date','Дата','datetime'),c('from_account','Счёт отправитель'),c('to_account','Счёт получатель'),c('amount','Сумма','money'),created],fields:[org,date,f('from_account','Со счёта','select',true,'cash-accounts/'),f('to_account','На счёт','select',true,'cash-accounts/'),f('amount','Сумма','money',true),comment],create:true,permission:'finance'},
  {key:'debts',title:'Задолженности',subtitle:'Дебиторская и кредиторская задолженность',endpoint:'debts/',icon:'Scale',columns:[c('counterparty','Контрагент'),c('debt_type','Тип','status'),c('amount','Начислено','money'),c('paid_amount','Оплачено','money'),c('due_date','Срок','date'),status],exportPath:'export/excel/debts/'},
  {key:'journal-entries',title:'Главная книга',subtitle:'Бухгалтерские проводки',endpoint:'journal-entries/',icon:'BookOpen',columns:[c('date','Дата','datetime'),c('description','Описание','text',true),c('document_type','Документ'),status,created],fields:[org,date,f('description','Описание','text',true),f('document_type','Тип документа')],create:true,permission:'finance'},
  {key:'leads',title:'Лиды',subtitle:'Потенциальные клиенты и квалификация',endpoint:'crm/leads/',icon:'Sparkles',columns:[c('name','Лид','text',true),c('phone','Телефон'),c('source','Источник'),c('expected_amount','Потенциал','money'),c('probability','Вероятность','number'),status,created],fields:[org,name,f('phone','Телефон'),f('email','Email'),f('source','Источник'),f('expected_amount','Ожидаемая сумма','money'),f('probability','Вероятность, %','number'),f('notes','Заметки','textarea')],create:true,edit:true},
  {key:'deals',title:'Сделки',subtitle:'Воронка и прогноз продаж',endpoint:'crm/deals/',icon:'GitBranch',columns:[c('title','Сделка','text',true),c('customer','Клиент'),c('stage','Этап'),c('expected_amount','Сумма','money'),c('probability','Вероятность','number'),status],fields:[org,f('title','Название','text',true),f('customer','Клиент','select',true,'counterparties/'),f('stage','Этап','select',false,'crm/deal-stages/'),f('expected_amount','Сумма','money'),f('probability','Вероятность, %','number')],create:true,edit:true},
  {key:'deal-stages',title:'Этапы сделок',subtitle:'Настройка воронки',endpoint:'crm/deal-stages/',icon:'Columns3',columns:[c('name','Этап','text',true),c('position','Позиция','number'),c('is_closed','Закрывающий','boolean')],fields:[org,name,f('position','Позиция','number'),f('is_closed','Закрывающий этап','boolean')],create:true,edit:true},
  {key:'crm-tasks',title:'Задачи CRM',subtitle:'План работ с клиентами',endpoint:'crm/tasks/',icon:'ListTodo',columns:[c('title','Задача','text',true),c('deal','Сделка'),c('assigned_to','Ответственный'),c('due_at','Срок','datetime'),status],fields:[org,f('title','Задача','text',true),f('deal','Сделка','select',false,'crm/deals/'),f('assigned_to','Ответственный','select',false,'employees/'),f('due_at','Срок','datetime')],create:true,edit:true},
  {key:'employees',title:'Сотрудники',subtitle:'Команда, должности и контакты',endpoint:'employees/',icon:'ContactRound',columns:[c('first_name','Имя','text',true),c('last_name','Фамилия'),c('department','Отдел'),c('position','Должность'),c('phone','Телефон'),c('salary','Оклад','money'),status],fields:[org,f('first_name','Имя','text',true),f('last_name','Фамилия','text',true),f('hire_date','Дата приёма','date',true),f('department','Отдел','select',false,'departments/'),f('position','Должность','select',false,'positions/'),f('phone','Телефон'),f('email','Email'),f('salary','Оклад','money')],create:true,edit:true,permission:'hr',exportPath:'export/excel/employees/'},
  {key:'departments',title:'Отделы',subtitle:'Организационная структура',endpoint:'departments/',icon:'Network',columns:[c('name','Отдел','text',true),c('description','Описание')],fields:[org,name,f('description','Описание','textarea')],create:true,edit:true,permission:'hr'},
  {key:'positions',title:'Должности',subtitle:'Штатные позиции',endpoint:'positions/',icon:'BriefcaseBusiness',columns:[c('name','Должность','text',true),c('description','Описание')],fields:[org,name,f('description','Описание','textarea')],create:true,edit:true,permission:'hr'},
  {key:'salary-payments',title:'Зарплата',subtitle:'Начисления и выплаты',endpoint:'salary-payments/',icon:'Banknote',columns:[c('employee','Сотрудник'),c('month','Период','date'),c('base_salary','Оклад','money'),c('bonus','Премия','money'),c('deduction','Удержание','money'),c('amount','К выплате','money'),status],fields:[f('employee','Сотрудник','select',true,'employees/'),f('month','Месяц','date',true),f('base_salary','Оклад','money'),f('bonus','Премия','money'),f('deduction','Удержание','money'),f('amount','Итого','money',true)],create:true,permission:'hr'},
  {key:'organizations',title:'Компании',subtitle:'Юридические лица и реквизиты',endpoint:'organizations/',icon:'Building2',columns:[c('name','Компания','text',true),c('inn','ИНН'),c('phone','Телефон'),c('email','Email'),c('currency','Валюта'),c('is_active','Активна','boolean')],fields:[name,f('full_name','Полное название'),f('inn','ИНН'),f('phone','Телефон'),f('email','Email'),f('address','Адрес'),f('currency','Валюта')],create:true,edit:true,permission:'admin'},
  {key:'branches',title:'Филиалы',subtitle:'Офисы и подразделения',endpoint:'branches/',icon:'MapPin',columns:[c('name','Филиал','text',true),c('organization','Компания'),c('phone','Телефон'),c('address','Адрес'),c('is_active','Активен','boolean')],fields:[org,name,f('phone','Телефон'),f('email','Email'),f('address','Адрес')],create:true,edit:true,permission:'admin'},
  {key:'organization-members',title:'Пользователи и роли',subtitle:'Доступ к организациям',endpoint:'organization-members/',icon:'ShieldCheck',columns:[c('user','Пользователь'),c('organization','Компания'),c('branch','Филиал'),c('role','Роль','status'),c('is_active','Активен','boolean'),c('joined_at','Добавлен','date')],fields:[org,f('user','Пользователь ID','number',true),f('branch','Филиал','select',false,'branches/'),f('role','Роль','select',true),f('is_active','Активен','boolean')],create:true,edit:true,permission:'admin'},
  {key:'audit-logs',title:'Журнал действий',subtitle:'История изменений и событий безопасности',endpoint:'audit-logs/',icon:'ScanEye',columns:[c('created_at','Дата','datetime'),c('user','Пользователь'),c('action','Действие','status'),c('model_name','Модуль'),c('object_id','Объект'),c('ip_address','IP'),c('description','Детали')]},
  {key:'notifications',title:'Уведомления',subtitle:'События, требующие внимания',endpoint:'notifications/',icon:'Bell',columns:[c('created_at','Дата','datetime'),c('notification_type','Тип','status'),c('title','Событие','text',true),c('message','Сообщение'),c('is_read','Прочитано','boolean')]},
]

export const resourceMap = Object.fromEntries(resources.map(r=>[r.key,r])) as Record<string,Resource>
export const resourceList = resources

export const navigation = [
  { label:'Обзор', items:[['Дашборд','/','LayoutDashboard']] },
  { label:'Продажи', items:[['Заказы','/m/sales','ReceiptText'],['Клиенты','/m/customers','UsersRound'],['Возвраты','/m/sale-returns','RotateCcw'],['POS / касса','/pos','ScanLine']] },
  { label:'Закупки', items:[['Заказы поставщикам','/m/purchases','ShoppingBag'],['Поставщики','/m/suppliers','Truck'],['Возвраты','/m/purchase-returns','Undo2']] },
  { label:'Каталог', items:[['Товары','/m/products','Package'],['Категории','/m/categories','Layers3'],['Бренды','/m/brands','BadgeCheck'],['Единицы','/m/units','Ruler'],['Прайс-листы','/m/price-types','Tags']] },
  { label:'Склад', items:[['Обзор склада','/inventory','Warehouse'],['Склады','/m/warehouses','Warehouse'],['Остатки','/m/stocks','Boxes'],['Движения','/m/stock-movements','ArrowLeftRight'],['Перемещения','/m/stock-transfers','MoveHorizontal'],['Инвентаризация','/m/inventories','ClipboardList'],['Списания','/m/write-offs','PackageX']] },
  { label:'Финансы', items:[['Обзор финансов','/finance','ChartNoAxesCombined'],['Кассы и счета','/m/cash-accounts','Landmark'],['Платежи','/m/cash-transactions','WalletCards'],['Переводы','/m/money-transfers','ArrowRightLeft'],['Долги','/m/debts','Scale'],['Главная книга','/m/journal-entries','BookOpen']] },
  { label:'CRM', items:[['Воронка','/crm','GitBranch'],['Лиды','/m/leads','Sparkles'],['Сделки','/m/deals','Handshake'],['Задачи','/m/crm-tasks','ListTodo'],['Этапы','/m/deal-stages','Columns3']] },
  { label:'Сотрудники', items:[['Команда','/m/employees','ContactRound'],['Отделы','/m/departments','Network'],['Должности','/m/positions','BriefcaseBusiness'],['Зарплата','/m/salary-payments','Banknote']] },
  { label:'Аналитика', items:[['Центр отчётов','/reports','BarChart3']] },
  { label:'Организация', items:[['Компании','/m/organizations','Building2'],['Филиалы','/m/branches','MapPin'],['Пользователи и роли','/m/organization-members','ShieldCheck']] },
  { label:'Система', items:[['Уведомления','/m/notifications','Bell'],['Журнал действий','/m/audit-logs','ScanEye'],['Настройки','/settings','Settings2']] },
] as { label: string; items: [string, string, string][] }[]
