# Generated by Django 6.1.1 on 2026-09-25 12:03

import django.db.models.deletion
from django.db import migrations, models


def update_debt_types(apps, schema_editor):
    debts = apps.get_model('myapp', 'Debt').objects.using(schema_editor.connection.alias)
    debts.filter(debt_type='RECEIVABLE').update(debt_type='CUSTOMER')
    debts.filter(debt_type='PAYABLE').update(debt_type='SUPPLIER')


def restore_debt_types(apps, schema_editor):
    debts = apps.get_model('myapp', 'Debt').objects.using(schema_editor.connection.alias)
    debts.filter(debt_type='CUSTOMER').update(debt_type='RECEIVABLE')
    debts.filter(debt_type='SUPPLIER').update(debt_type='PAYABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchasereturn_purchasereturnitem_salereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.purchase'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sale'),
        ),
        migrations.AddField(
            model_name='debt',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.purchase'),
        ),
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sale'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.cashaccount'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.cashaccount'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20),
        ),
        migrations.RunPython(update_debt_types, restore_debt_types),
    ]
