# Generated by Django 6.1.1 on 2026-09-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cashtransaction_purchase_cashtransaction_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.cashaccount'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
