# Generated by Django 6.1.1 on 2026-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход'), ('TRANSFER_IN', 'Перемещение приход'), ('TRANSFER_OUT', 'Перемещение расход'), ('WRITE_OFF', 'Списание'), ('INVENTORY', 'Инвентаризация'), ('RETURN_IN', 'Возврат продажи'), ('RETURN_OUT', 'Возврат поставщику')], max_length=30),
        ),
    ]
