# Generated by Django 6.1.1 on 2026-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_account_crmactivity_crmtask_deal_dealstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Касса'), ('BANK', 'Банк'), ('WALLET', 'Wallet'), ('CARD', 'Карта'), ('OTHER', 'Другое')], max_length=20),
        ),
    ]
