# Generated by Django 6.1.1 on 2026-09-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='break_room_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='break_room_games_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='break_room_pet_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BreakRoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('show_pet_on_dashboard', models.BooleanField(default=False)),
                ('reminders', models.CharField(choices=[('NEVER', 'Never'), ('RARELY', 'Rarely'), ('SOMETIMES', 'Sometimes'), ('OFTEN', 'Often')], default='NEVER', max_length=12)),
                ('pet_sound', models.BooleanField(default=False)),
                ('pet_animations', models.BooleanField(default=True)),
                ('nature_autoplay', models.BooleanField(default=False)),
                ('default_duration', models.PositiveSmallIntegerField(default=5)),
                ('focus_mode', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('volume', models.PositiveSmallIntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='break_room_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('nature', 'Nature'), ('sound', 'Sound'), ('game', 'Game'), ('pet', 'Pet'), ('breathing', 'Breathing')], max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('animal_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('fox', 'Fox'), ('panda', 'Panda'), ('rabbit', 'Rabbit'), ('bear', 'Bear'), ('wolf', 'Wolf')], max_length=16)),
                ('personality', models.CharField(choices=[('friendly', 'Friendly'), ('funny', 'Funny'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('motivating', 'Motivating'), ('smart', 'Smart'), ('sarcastic-light', 'Sarcastic-Light')], default='friendly', max_length=20)),
                ('communication_style', models.CharField(choices=[('short', 'Short'), ('normal', 'Normal'), ('talkative', 'Talkative')], default='normal', max_length=12)),
                ('color', models.CharField(default='sand', max_length=24)),
                ('eyes', models.CharField(default='warm', max_length=24)),
                ('ears', models.CharField(default='classic', max_length=24)),
                ('accessory', models.CharField(blank=True, max_length=24)),
                ('clothes', models.CharField(blank=True, max_length=24)),
                ('background', models.CharField(default='meadow', max_length=24)),
                ('mood', models.CharField(default='calm', max_length=12)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='break_room_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('pet', 'Pet')], max_length=4)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoundPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sounds', models.JSONField(default=dict)),
                ('master_volume', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
