import { createContext, useContext, useState, type ButtonHTMLAttributes, type ReactNode } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { cva, type VariantProps } from 'class-variance-authority'
import { CheckCircle2, AlertCircle, X, Search, LoaderCircle } from 'lucide-react'
import { twMerge } from 'tailwind-merge'

const styles = cva('inline-flex items-center justify-center gap-2 rounded-lg font-semibold transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 disabled:pointer-events-none disabled:opacity-50', { variants: { variant: { primary:'bg-primary text-white hover:bg-primary/90',secondary:'border border-border bg-card text-foreground hover:bg-muted',ghost:'text-slate-500 hover:bg-muted hover:text-foreground',danger:'border border-rose-200 bg-rose-50 text-rose-700 hover:bg-rose-100 dark:border-rose-900 dark:bg-rose-950',outline:'border border-border text-foreground hover:bg-muted' }, size:{sm:'h-8 px-3 text-xs',default:'h-9 px-4 text-sm',lg:'h-11 px-5 text-sm',icon:'h-9 w-9'} },defaultVariants:{variant:'secondary',size:'default'} })
export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof styles>
export function Button({ variant,size,className,...props }:ButtonProps) { return <button className={twMerge(styles({variant,size}),className)} {...props}/> }
export function Badge({ children, tone='neutral' }:{children:ReactNode;tone?:'success'|'warning'|'danger'|'info'|'neutral'}) { return <span className={`badge badge-${tone}`}>{children}</span> }
export function StatusBadge({ value }:{value:unknown}) { const text=String(value??'—');const translations:Record<string,string>={DRAFT:'Черновик',POSTED:'Проведён',PAID:'Оплачен',PARTIAL:'Частично',UNPAID:'Не оплачен',OPEN:'Открыт',DONE:'Выполнен',ACTIVE:'Активен',CANCELLED:'Отменён',WON:'Успешно',LOST:'Проигран',INCOME:'Доход',EXPENSE:'Расход',CUSTOMER:'Клиент',SUPPLIER:'Поставщик'};const tone=['POSTED','PAID','DONE','ACTIVE','WON','INCOME'].includes(text)?'success':['PARTIAL','OPEN','DRAFT','UNPAID'].includes(text)?'warning':['CANCELLED','LOST','EXPENSE'].includes(text)?'danger':'info';return <Badge tone={tone}>{translations[text]||text}</Badge> }
export function PageHeader({ eyebrow, title, description, actions }:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}) { return <div className="page-header"><div><div className="eyebrow">{eyebrow||'РАБОЧЕЕ ПРОСТРАНСТВО / NEXORA ERP'}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div> }
export function StatCard({ label, value, hint, icon, tone='primary' }:{label:string;value:ReactNode;hint?:ReactNode;icon?:ReactNode;tone?:'primary'|'success'|'warning'|'danger'}) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon tone-${tone}`}>{icon}</span></div><div className="stat-value">{value}</div><div className="stat-hint">{hint||'Актуальные данные'}</div></div> }
export function EmptyState({ title='Данных пока нет', description='Записи появятся здесь после создания.', action }:{title?:string;description?:string;action?:ReactNode}) { return <div className="empty-state"><div className="empty-icon"><Search size={22}/></div><strong>{title}</strong><p>{description}</p>{action}</div> }
export function LoadingSkeleton({ lines=6 }:{lines?:number}) { return <div className="skeleton-list" aria-label="Загрузка">{Array.from({length:lines},(_,i)=><div key={i} className="skeleton-row" style={{width:`${95-i%3*8}%`}}/>)}</div> }
export function ErrorState({ error, retry }:{error:string;retry?:()=>void}) { return <div className="empty-state"><div className="empty-icon error"><AlertCircle size={22}/></div><strong>Не удалось загрузить данные</strong><p>{error}</p>{retry&&<Button onClick={retry}>Повторить</Button>}</div> }
export function FormSection({ title, subtitle, children }:{title:string;subtitle?:string;children:ReactNode}) { return <section className="surface form-section"><div className="section-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section> }
export function ConfirmDialog({ open,onOpenChange,title='Вы уверены?',description,confirmLabel='Подтвердить',danger=false,onConfirm }:{open:boolean;onOpenChange:(v:boolean)=>void;title?:string;description:string;confirmLabel?:string;danger?:boolean;onConfirm:()=>void}) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><Dialog.Title className="dialog-title">{title}</Dialog.Title><Dialog.Description className="dialog-description">{description}</Dialog.Description><div className="dialog-actions"><Button onClick={()=>onOpenChange(false)}>Отмена</Button><Button variant={danger?'danger':'primary'} onClick={()=>{onConfirm();onOpenChange(false)}}>{confirmLabel}</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root> }
type Notice = {id:number;message:string;type:'success'|'error'}
const ToastContext = createContext<{toast:(message:string,type?:'success'|'error')=>void}|null>(null)
export function ToastProvider({children}:{children:ReactNode}) {const [items,setItems]=useState<Notice[]>([]);const toast=(message:string,type:'success'|'error'='success')=>{const id=Date.now()+Math.random();setItems(old=>[...old,{id,message,type}]);setTimeout(()=>setItems(old=>old.filter(x=>x.id!==id)),4000)};return <ToastContext.Provider value={{toast}}>{children}<div className="toast-stack" role="status">{items.map(item=><div key={item.id} className={`toast toast-${item.type}`}>{item.type==='success'?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<span>{item.message}</span><button onClick={()=>setItems(old=>old.filter(x=>x.id!==item.id))} aria-label="Закрыть"><X size={15}/></button></div>)}</div></ToastContext.Provider>}
export const useToast=()=>{const context=useContext(ToastContext);if(!context)throw new Error('ToastProvider missing');return context.toast}
export function SearchInput({value,onChange,placeholder='Поиск…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}) {return <label className="search-input"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button aria-label="Очистить" onClick={()=>onChange('')}><X size={14}/></button>}</label>}
export function Spinner(){return <LoaderCircle size={16} className="animate-spin"/>}
