from django.urls import path
from .views import *
from .reports import *
from .exports import *
from .excel_exports import *

urlpatterns = [
    path('organizations/', OrganizationListCreateView.as_view()),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view()),
    path('branches/', BranchListCreateView.as_view()),
    path('branches/<int:pk>/', BranchDetailView.as_view()),
    path('organization-members/', OrganizationMemberListCreateView.as_view()),
    path('organization-members/<int:pk>/', OrganizationMemberDetailView.as_view()),

    path('departments/', DepartmentListCreateView.as_view()),
    path('departments/<int:pk>/', DepartmentDetailView.as_view()),
    path('positions/', PositionListCreateView.as_view()),
    path('positions/<int:pk>/', PositionDetailView.as_view()),
    path('employees/', EmployeeListCreateView.as_view()),
    path('employees/<int:pk>/', EmployeeDetailView.as_view()),
    path('salary-payments/', SalaryPaymentListCreateView.as_view()),
    path('salary-payments/<int:pk>/', SalaryPaymentDetailView.as_view()),
    path('salary-payments/<int:pk>/pay/', PaySalaryView.as_view()),
    path('salary-payments/generate/', GenerateSalaryPaymentsView.as_view()),

    path('counterparties/', CounterpartyListCreateView.as_view()),
    path('counterparties/<int:pk>/', CounterpartyDetailView.as_view()),
    path('contact-persons/', ContactPersonListCreateView.as_view()),
    path('contact-persons/<int:pk>/', ContactPersonDetailView.as_view()),

    path('categories/', CategoryListCreateView.as_view()),
    path('categories/<int:pk>/', CategoryDetailView.as_view()),
    path('units/', UnitListCreateView.as_view()),
    path('units/<int:pk>/', UnitDetailView.as_view()),
    path('brands/', BrandListCreateView.as_view()),
    path('brands/<int:pk>/', BrandDetailView.as_view()),
    path('products/', ProductListCreateView.as_view()),
    path('products/<int:pk>/', ProductDetailView.as_view()),
    path('products/<int:pk>/archive/', ProductArchiveView.as_view()),
    path('price-types/', PriceTypeListCreateView.as_view()),
    path('price-types/<int:pk>/', PriceTypeDetailView.as_view()),
    path('product-prices/', ProductPriceListCreateView.as_view()),
    path('product-prices/<int:pk>/', ProductPriceDetailView.as_view()),

    path('warehouses/', WarehouseListCreateView.as_view()),
    path('warehouses/<int:pk>/', WarehouseDetailView.as_view()),
    path('stocks/', StockListView.as_view()),
    path('stocks/<int:pk>/', StockDetailView.as_view()),
    path('stock-movements/', StockMovementListView.as_view()),
    path('stock-reservations/', StockReservationListCreateView.as_view()),
    path('stock-reservations/<int:pk>/release/', ReleaseStockReservationView.as_view()),

    path('purchases/', PurchaseListCreateView.as_view()),
    path('purchases/<int:pk>/', PurchaseDetailView.as_view()),
    path('purchase-items/', PurchaseItemListCreateView.as_view()),
    path('purchase-items/<int:pk>/', PurchaseItemDetailView.as_view()),
    path('purchases/<int:pk>/post/', PostPurchaseView.as_view()),
    path('purchases/<int:pk>/unpost/', UnpostPurchaseView.as_view()),
    path('purchases/<int:pk>/cancel/', CancelPurchaseView.as_view()),

    path('sales/', SaleListCreateView.as_view()),
    path('sales/<int:pk>/', SaleDetailView.as_view()),
    path('sale-items/', SaleItemListCreateView.as_view()),
    path('sale-items/<int:pk>/', SaleItemDetailView.as_view()),
    path('sales/<int:pk>/post/', PostSaleView.as_view()),
    path('sales/<int:pk>/unpost/', UnpostSaleView.as_view()),
    path('sales/<int:pk>/cancel/', CancelSaleView.as_view()),

    path('stock-transfers/', StockTransferListCreateView.as_view()),
    path('stock-transfers/<int:pk>/', StockTransferDetailView.as_view()),
    path('stock-transfer-items/', StockTransferItemListCreateView.as_view()),
    path('stock-transfer-items/<int:pk>/', StockTransferItemDetailView.as_view()),
    path('stock-transfers/<int:pk>/post/', PostStockTransferView.as_view()),
    path('stock-transfers/<int:pk>/unpost/', UnpostStockTransferView.as_view()),

    path('write-offs/', WriteOffListCreateView.as_view()),
    path('write-offs/<int:pk>/', WriteOffDetailView.as_view()),
    path('write-off-items/', WriteOffItemListCreateView.as_view()),
    path('write-off-items/<int:pk>/', WriteOffItemDetailView.as_view()),
    path('write-offs/<int:pk>/post/', PostWriteOffView.as_view()),
    path('write-offs/<int:pk>/unpost/', UnpostWriteOffView.as_view()),

    path('inventories/', InventoryListCreateView.as_view()),
    path('inventories/<int:pk>/', InventoryDetailView.as_view()),
    path('inventory-items/', InventoryItemListCreateView.as_view()),
    path('inventory-items/<int:pk>/', InventoryItemDetailView.as_view()),
    path('inventories/<int:pk>/post/', PostInventoryView.as_view()),
    path('inventories/<int:pk>/unpost/', UnpostInventoryView.as_view()),

    path('cash-accounts/', CashAccountListCreateView.as_view()),
    path('cash-accounts/<int:pk>/', CashAccountDetailView.as_view()),
    path('finance-categories/', FinanceCategoryListCreateView.as_view()),
    path('finance-categories/<int:pk>/', FinanceCategoryDetailView.as_view()),
    path('cash-transactions/', CashTransactionListCreateView.as_view()),
    path('cash-transactions/<int:pk>/', CashTransactionDetailView.as_view()),
    path('cash-transactions/<int:pk>/post/', PostCashTransactionView.as_view()),
    path('cash-transactions/<int:pk>/unpost/', UnpostCashTransactionView.as_view()),

    path('money-transfers/', MoneyTransferListCreateView.as_view()),
    path('money-transfers/<int:pk>/', MoneyTransferDetailView.as_view()),

    path('debts/', DebtListCreateView.as_view()),
    path('debts/<int:pk>/', DebtDetailView.as_view()),
    path('debts/<int:pk>/pay/', PayDebtView.as_view()),
    path('debt-payments/', DebtPaymentListView.as_view()),

    path('accounts/', AccountListCreateView.as_view()),
    path('accounts/<int:pk>/', AccountDetailView.as_view()),
    path('journal-entries/', JournalEntryListCreateView.as_view()),
    path('journal-entries/<int:pk>/', JournalEntryDetailView.as_view()),
    path('journal-entry-lines/', JournalEntryLineListCreateView.as_view()),
    path('journal-entry-lines/<int:pk>/', JournalEntryLineDetailView.as_view()),
    path('journal-entries/<int:pk>/post/', PostJournalEntryView.as_view()),
    path('journal-entries/<int:pk>/cancel/', CancelJournalEntryView.as_view()),

    path('crm/deal-stages/', DealStageListCreateView.as_view()),
    path('crm/deal-stages/<int:pk>/', DealStageDetailView.as_view()),
    path('crm/leads/', LeadListCreateView.as_view()),
    path('crm/leads/<int:pk>/', LeadDetailView.as_view()),
    path('crm/leads/<int:pk>/convert/', ConvertLeadView.as_view()),
    path('crm/deals/', DealListCreateView.as_view()),
    path('crm/deals/<int:pk>/', DealDetailView.as_view()),
    path('crm/tasks/', CRMTaskListCreateView.as_view()),
    path('crm/tasks/<int:pk>/', CRMTaskDetailView.as_view()),
    path('crm/activities/', CRMActivityListCreateView.as_view()),
    path('crm/activities/<int:pk>/', CRMActivityDetailView.as_view()),

    path('notifications/', NotificationListView.as_view()),
    path('notifications/unread/', UnreadNotificationListView.as_view()),
    path('notifications/<int:pk>/read/', ReadNotificationView.as_view()),
    path('notifications/read-all/', ReadAllNotificationsView.as_view()),
    path('notifications/check-low-stock/', CheckLowStockView.as_view()),

    path('audit-logs/', AuditLogListView.as_view()),
    path('audit-logs/<int:pk>/', AuditLogDetailView.as_view()),

    path('dashboard/',DashboardView.as_view()),
    path('reports/sales/',SalesReportView.as_view()),
    path('reports/purchases/',PurchaseReportView.as_view()),
    path('reports/finance/',FinanceReportView.as_view()),
    path('reports/debts/',DebtReportView.as_view()),
    path('reports/stocks/',StockReportView.as_view()),
    path('reports/low-stock/',LowStockReportView.as_view()),
    path('reports/top-products/',TopProductsReportView.as_view()),
    path('reports/monthly-sales/',MonthlySalesReportView.as_view()),
    path('reports/stock-movements/',StockMovementReportView.as_view()),
    path('reports/sales-by-category/',SalesByCategoryReportView.as_view()),
    path('reports/sales-by-employee/',SalesByEmployeeReportView.as_view()),
    path('reports/top-customers/',TopCustomersReportView.as_view()),
    path('reports/salaries/',SalaryReportView.as_view()),

    path('sale-returns/',SaleReturnListCreateView.as_view()),
    path('sale-returns/<int:pk>/',SaleReturnDetailView.as_view()),
    path('sale-return-items/',SaleReturnItemListCreateView.as_view()),
    path('sale-returns/<int:pk>/post/',PostSaleReturnView.as_view()),
    path('purchase-returns/',PurchaseReturnListCreateView.as_view()),
    path('purchase-returns/<int:pk>/',PurchaseReturnDetailView.as_view()),
    path('purchase-return-items/',PurchaseReturnItemListCreateView.as_view()),
    path('purchase-returns/<int:pk>/post/',PostPurchaseReturnView.as_view()),
    path('reports/profit/',ProfitReportView.as_view()),
    path('reports/product-profit/',ProductProfitReportView.as_view()),
    path('reports/daily-profit/',DailyProfitReportView.as_view()),
    path('reports/monthly-profit/',MonthlyProfitReportView.as_view()),
    path('export/products/',ExportProductsView.as_view()),
    path('export/stocks/',ExportStocksView.as_view()),
    path('export/sales/',ExportSalesView.as_view()),
    path('export/purchases/',ExportPurchasesView.as_view()),
    path('export/debts/',ExportDebtsView.as_view()),
    path('export/employees/',ExportEmployeesView.as_view()),
    path('export/cash-transactions/',ExportCashTransactionsView.as_view()),
    path('export/excel/products/',ExportProductsExcelView.as_view()),
    path('export/excel/stocks/',ExportStocksExcelView.as_view()),
    path('export/excel/sales/',ExportSalesExcelView.as_view()),
    path('export/excel/purchases/',ExportPurchasesExcelView.as_view()),
    path('export/excel/debts/',ExportDebtsExcelView.as_view()),
    path('export/excel/employees/',ExportEmployeesExcelView.as_view()),
    path('export/excel/cash-transactions/',ExportCashTransactionsExcelView.as_view()),
]
